# -*- coding: utf-8 -*-
"""moodmedic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H3OeSjRcrKR6Fomhlzg5tV8ZM7i3OJlx
"""

import numpy as np

# Each question has:
# - text: the question to ask
# - category: "stability" or "efficiency"
# - weight: importance of the question in scoring

questions = [
    {"text": "Did you sleep well last night?", "category": "stability", "weight": 0.2},
    {"text": "Do you feel anxious today?", "category": "stability", "weight": -0.2},
    {"text": "Do you feel motivated to work?", "category": "efficiency", "weight": 0.3},
    {"text": "Do you feel physically energetic?", "category": "stability", "weight": 0.2},
    {"text": "Are you able to focus easily?", "category": "efficiency", "weight": 0.25},
    {"text": "Do you feel socially connected?", "category": "stability", "weight": 0.15},
    {"text": "Do you feel overwhelmed by tasks?", "category": "efficiency", "weight": -0.2},
]

answers = []

print("🌙 Mood Medic — Daily Emotional Check")
print("Answer Yes/No and give intensity from 1 to 10.\n")

for q in questions:
    yn = input(f"{q['text']} (Yes/No): ").strip().lower()
    intensity = int(input("   Intensity (1-10): "))
    yn_val = 1 if yn == "yes" else 0

    answers.append({
        "question": q["text"],
        "category": q["category"],
        "weight": q["weight"],
        "yn": yn_val,
        "intensity": intensity/10  # normalize 0-1
    })

#scoring function
def calculate_scores(answers):
    stability_score = 0
    efficiency_score = 0

    for ans in answers:
        contribution = ans["yn"] * ans["intensity"] * ans["weight"] * 100
        if ans["category"] == "stability":
            stability_score += contribution
        else:
            efficiency_score += contribution

    # Normalize scores to 0–100 range
    stability_score = max(0, min(100, stability_score + 50))  # baseline at 50
    efficiency_score = max(0, min(100, efficiency_score + 50))

    return stability_score, efficiency_score

#generate report
stability, efficiency = calculate_scores(answers)

print("\n📝 Mood Medic Report")
print(f"Emotional Stability Score: {stability:.1f}/100")
print(f"Efficiency Score: {efficiency:.1f}/100")

# Simple recommendations
if stability < 50:
    print("⚠️ You're showing low stability. Try meditation or journaling today.")
elif stability < 70:
    print("🙂 Stability is okay, but be mindful of stress triggers.")
else:
    print("💪 You're emotionally stable today!")

if efficiency < 50:
    print("⚠️ Low efficiency detected. Break tasks into smaller steps.")
elif efficiency < 70:
    print("⚡ Moderate efficiency. A short walk may help boost focus.")
else:
    print("🚀 You're set for a highly efficient day!")

import matplotlib.pyplot as plt

# Simulated scores (pretend these are from 5 days of answers)
days = ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5"]
stability_scores = [60, 55, 70, 65, 75]
efficiency_scores = [50, 60, 55, 70, 65]

plt.figure(figsize=(8,5))
plt.plot(days, stability_scores, label="Stability", marker='o')
plt.plot(days, efficiency_scores, label="Efficiency", marker='o')
plt.title("Mood Medic: Sample Performance Over 5 Days")
plt.xlabel("Days")
plt.ylabel("Score (0-100)")
plt.legend()
plt.show()